### ISSUE TITLE
bind-address override not working is using docker-compose 

### ISSUE THREAD

**Issue by bencivennil** [mattrayner/docker-lamp#117]
Hi all, 

if I start a container using docker-compose the value of bind-address is not what I expect to be looking at the dockerfile

this is my docker-compose.yml
```
services:    
  web:
    build: ./<path-to-dockerfile>
    container_name: mycontainer
```
in the docker file I use the `latest-1604-php5` tag

after starting the container (everything seems almost good) I start the bash into it and I log into mysql using

`mysql -u root`

if I run the query

`show variables like '%bind%';`

the value is 127.0.0.1 and 0.0.0.0 as I would expect it to be.

If I run che image using `docker run`

the value of the variable is 0.0.0.0

Am I missing something? 

Thanks,
Luca
