### ISSUE TITLE
Waiting for confirmation of MySQL service startup

### ISSUE THREAD

**Issue by phenixita** [mattrayner/docker-lamp#118]
Hi!

if I run the image inside a kubernetes cluster it gets stuck at:

Waiting for confirmation of MySQL service startup

![image](https://user-images.githubusercontent.com/17789308/121359186-83ff6500-c933-11eb-8512-ea911dabcad2.png)

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myphpapp
spec:
  selector:
    matchLabels:
      app: myphpapp
  template:
    metadata:
      labels:
        app: myphpapp
    spec:
      containers:
      - name: myphpapp
        image: mattrayner/lamp:latest-1804
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myphpapp
spec:
  type: LoadBalancer
  selector:
    app: myphpapp
  ports:
  - port: 8888
    targetPort: 80

```

![image](https://user-images.githubusercontent.com/17789308/121361292-71862b00-c935-11eb-9b42-37306f0f0565.png)
