### ISSUE TITLE
Gitlab CI connect to local MySQL server

### ISSUE THREAD

**Issue by pimvanderheijden** [mattrayner/docker-lamp#134]
Hi!

Again, really fantastic image! Seems like I'm pushing it to it's limits :smile:

Trying to do some stuff with it in Gitlab CI. Apache appears to be up and running so that's a good start. Unfortunately the MySQL connection doesn't work (yet).  

I'm using this image as a service, which I think is the preferred method here. Especially considering I'm testing a NodeJS script against my lamp application.

```
stages:
  - install
  - test

install:
  image: node:14
  stage: install
  artifacts:
    paths:
      - app
  script:
    - mkdir app
    - find . -mindepth 1 -type f -exec cp --parents -t app {} + # copy files to app
    - cd app
    - npm ci --omit=optional --cache .npm --prefer-offline

test:
  image: node:14
  stage: test
  needs:
    - job: install
      artifacts: true
  services:
    - name: mattrayner/lamp:0.8.0-2004-php7
      alias: my-app
      entrypoint: [
        "/run.sh",
        # "bash service apache2 restart", # ?
        "sleep 25", # ?
        "mysql -h my-app -u root -e \"CREATE DATABASE joeyclz119_mvt\";",
        "mysql -h my-app -D joeyclz119_mvt < joeyclz119_mvt_empty_tables.sql;",
        "mysql -h my-app -u root -e \"SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''))\""
      ]
  script:
    # - sleep 30 # ?
    - cd app
    - HOST=http://my-app:80 npm run test:ci
```

Whatever settings I try, I keep getting this error:
```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

From my test script the Apache server gives me back an error:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL was not found on this server.</p>
<hr>
<address>Apache/2.4.41 (Ubuntu) Server at localhost Port 80</address>
</body></html>
```

I think this last error could be related to MySQL because when I do `service apache2 status`, I get: 
```
 * apache2 is running
 ```
 
 Am I doing something wrong?

**Comment by pzhlkj6612** [comment]
Hello!

```YAML
stages:
  - test

test:
  image: node:14
  stage: test
  services:
    - name: mattrayner/lamp:0.8.0-2004-php7
      alias: my-app
      entrypoint: [
        "/run.sh",
        "sleep 25",
        "mysql -h my-app -u root -e \"CREATE DATABASE joeyclz119_mvt\";",
        "mysql -h my-app -D joeyclz119_mvt < joeyclz119_mvt_empty_tables.sql;",
        "mysql -h my-app -u root -e \"SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'ONLY_FULL_GROUP_BY',''))\""
      ]
  script:
    - curl 'http://my-app:80'

```

Maybe you can try fetching the webpage with CURL directly to test your CI? It works on my side:

```
Running with gitlab-runner 16.4.1 (d89a789a)
  on runner10.0.0.13 S54WkQXfL, system ID: s_795c1f69ce65
section_start:1697988517:prepare_executor
Preparing the "docker" executor
Using Docker executor with image node:14 ...
Starting service mattrayner/lamp:0.8.0-2004-php7 ...
Pulling docker image mattrayner/lamp:0.8.0-2004-php7 ...
Using docker image sha256:18fb39335b266fa620548343b2aaded0e9b4bf8887f5859527c25e1c236d5245 for mattrayner/lamp:0.8.0-2004-php7 with digest mattrayner/lamp@sha256:2312406ac8bc843359bfdc6aeb7da996d9bc68232bf59483301fe0d763ca3097 ...
Waiting for services to be up and running (timeout 30 seconds)...

*** WARNING: Service runner-s54wkqxfl-project-1-concurrent-0-55abeb886119aff0-mattrayner__lamp-0 probably didn't start properly.

Health check error:
service "runner-s54wkqxfl-project-1-concurrent-0-55abeb886119aff0-mattrayner__lamp-0-wait-for-service" timeout

Health check container logs:
2023-10-22T15:30:21.283548489Z waiting for TCP connection to 172.17.0.2 on [3306 80]...
2023-10-22T15:30:21.296386714Z dialing 172.17.0.2:80...
2023-10-22T15:30:21.297500357Z dialing 172.17.0.2:3306...

...

2023-10-22T15:30:51.381870039Z dialing 172.17.0.2:3306...
2023-10-22T15:30:51.495327912Z dialing 172.17.0.2:80...

Service container logs:
2023-10-22T15:30:17.653340071Z Updating for PHP 7.4
2023-10-22T15:30:17.667914351Z Replacing CLI php.ini values
2023-10-22T15:30:17.675217570Z Editing APACHE_RUN_GROUP environment variable
2023-10-22T15:30:17.676484350Z Editing phpmyadmin config
2023-10-22T15:30:17.690249724Z Setting up MySQL directories
2023-10-22T15:30:17.698965739Z Allowing Apache/PHP to write to the app
2023-10-22T15:30:22.424736307Z Allowing Apache/PHP to write to MySQL
2023-10-22T15:30:22.442284597Z Editing MySQL config
2023-10-22T15:30:22.456442225Z => An empty or uninitialized MySQL volume is detected in /var/lib/mysql
2023-10-22T15:30:22.456474541Z => Installing MySQL ...
2023-10-22T15:30:42.454896062Z => Done!
2023-10-22T15:30:42.458908097Z => Waiting for confirmation of MySQL service startup
2023-10-22T15:30:47.640554165Z => Waiting for confirmation of MySQL service startup
2023-10-22T15:30:52.890529099Z => Waiting for confirmation of MySQL service startup
2023-10-22T15:30:57.989102555Z => Creating MySQL admin user with random password

*********

Pulling docker image node:14 ...
Using docker image sha256:1d12470fa662a2a5cb50378dcdc8ea228c1735747db410bbefb8e2d9144b5452 for node:14 with digest node@sha256:a158d3b9b4e3fa813fa6c8c590b8f0a860e015ad4e59bbce5744d2f6fd8461aa ...
section_end:1697988800:prepare_executor
section_start:1697988800:prepare_script
Preparing environment
Running on runner-s54wkqxfl-project-1-concurrent-0 via ubuntu-22043...
section_end:1697988808:prepare_script
section_start:1697988808:get_sources
Getting source from Git repository
Fetching changes with git depth set to 20...
Reinitialized existing Git repository in /builds/user/docker-lamp-test-0/.git/
Checking out c1324d78 as detached HEAD (ref is main)...
Removing app/

Skipping Git submodules setup
section_end:1697988815:get_sources
section_start:1697988815:step_script
Executing "step_script" stage of the job script
Using docker image sha256:1d12470fa662a2a5cb50378dcdc8ea228c1735747db410bbefb8e2d9144b5452 for node:14 with digest node@sha256:a158d3b9b4e3fa813fa6c8c590b8f0a860e015ad4e59bbce5744d2f6fd8461aa ...
$ curl 'http://my-app:80'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0<!doctype html>
<html lang=en>
<head>
    <meta charset=utf-8>
    <title>Hello World from Docker-LAMP</title>

    <style>
        @import 'https://fonts.googleapis.com/css?family=Montserrat|Raleway|Source+Code+Pro';

        body { font-family: 'Raleway', sans-serif; }
        h2 { font-family: 'Montserrat', sans-serif; }
        pre {
            font-family: 'Source Code Pro', monospace;

            padding: 16px;
            overflow: auto;
            font-size: 85%;
            line-height: 1.45;
            background-color: #f7f7f7;
            border-radius: 3px;

            word-wrap: normal;
        }

        .container {
            max-width: 1024px;
            width: 100%;
            margin: 0 auto;
        }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <img src="https://cdn.rawgit.com/mattrayner/docker-lamp/831976c022782e592b7e2758464b2a9efe3da042/docs/logo.svg" alt="Docker LAMP logo" />
            <h2>Welcome to <a href="https://github.com/mattrayner/docker-lamp" target="_blank">Docker-Lamp</a> a.k.a mattrayner/lamp</h2>
        </header>
        <article>
            <p>
                For documentation, <a href="https://github.com/mattrayner/docker-lamp" target="_blank">click here</a>.
            </p>
        </article>
        <section>
            <pre>
OS: Ubuntu 20.04.3 LTS<br/>
Apache: Apache/2.4.41 (Ubuntu)<br/>
MySQL Version: 8.0.26-0ubuntu0.20.04.2<br/>
PHP Version: 7.4.23<br/>
phpMyAdmin Version: 5.1.1            </pre>
        </section>
    </div>
</body>
</html>

100  1566  100  1566    0     0   9433      0 --:--:-- --:--:-- --:--:--  9433
section_end:1697988823:step_script
Job succeeded

```
