### ISSUE TITLE
use navicat connecting to mysql port failed: 2003 - can't connect to mysql server 10061 unknown error

### ISSUE THREAD

**Issue by chwech** [mattrayner/docker-lamp#42]
my Dockerfile and docker-compose.yml:
```
// dockerfile
FROM mattrayner/lamp:latest-1604
CMD ["/run.sh"]

// docker-compose.yml
version: "3"

services:
  lamp:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/home/chwech/tp5:/app"
      - "/home/chwech/mysql-data:/var/lib/mysql"
    ports:
      - "3306:3306"
      - "8081:80"
```
my container status:

![image](https://image-static.segmentfault.com/367/913/3679135607-5bcf2439197fb_articlex)

navicat and docker is in different machine. i can use admin user and phpmyadmin cannect to mysql, but navicat can't. how can i connect to mysql? thank you!
