### ISSUE TITLE
Get admin password after docker-compose up

### ISSUE THREAD

**Issue by CamilleHUmusic** [mattrayner/docker-lamp#73]
Hello, i have problem to get my admin password after docker-compose up.
I run docker-compose logs, but it does not show me password.
Thanks for you help

**Comment by pzhlkj6612** [comment]
What was printed when you run `docker-compose logs`?

**Comment by mattrayner** [comment]
@pzhlkj6612 thanks for replying, @CamilleHUmusic - did this help you at all?

**Comment by WhereJuly** [comment]
Looking at the original image's Dockerfile I see that defining the environment variables in the `docker-compose.yml` could work. E.g.:

**Comment by michaelseibt** [comment]
The hint of @WhereJuly actually works:

```
version: "3.1"

services:
  web:
    image: mattrayner/lamp:latest-1604-php7
    environment:
      - MYSQL_USER_NAME=mysql
      - MYSQL_USER_DB=mysql
      - MYSQL_USER_PASS=mysql
    ports:
      - 8080:80
    volumes:
      - ~/mysql:/var/lib/mysql
      - .:/app
```

Running this with `docker-compose up` will generate the following output when creating the MySQL instance:

```
web_1  | => An empty or uninitialized MySQL volume is detected in /var/lib/mysql
web_1  | => Installing MySQL ...
web_1  | => Done!
web_1  | => Waiting for confirmation of MySQL service startup
web_1  | => Creating MySQL admin user with random password
web_1  | ERROR 1133 (42000) at line 1: Can't find any matching row in the user table
web_1  | => Done!
web_1  | ========================================================================
web_1  | You can now connect to this MySQL Server with 2cGtTwbgjCqB
web_1  |
web_1  |     mysql -uadmin -p..... -h<host> -P<port>
web_1  |
web_1  | Please remember to change the above password as soon as possible!
web_1  | MySQL user 'root' has no password but only allows local connections
web_1  |
web_1  | We also created
web_1  | A database called 'mysql' and
web_1  | a user called 'mysql' with password 'mysql'
web_1  | 'mysql' has full access on 'mysql'
web_1  | enjoy!
web_1  | ========================================================================
```
